apiVersion: v1
kind: Pod
metadata:
  name: usa-pod
  labels:
    app: usa
spec:
  tolerations:
  - key: "key1"
    operator: "Equal"
    value: "value1"
    effect: "NoSchedule"
  containers:
  - name: my-container
    image: nginx