apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset-1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: Frontend
  template:
    metadata:
      labels:
        app: Frontend
    spec:
      containers:
      - name: nginx
        image: nginx
